services:
  backend:
    build: ./backend
    container_name: backend
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
      - sqlite_data:/app/db  # SQLite-DB persistieren
    ports:
      - "8000:8000"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  etl:
    build:
      context: ./backend/etl
      dockerfile: Dockerfile
    container_name: etl
    command: ["python", "main.py"]
    depends_on:
      - backend
    env_file:
      - .env

  frontend:
    build: ./frontend
    container_name: frontend
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"
    depends_on:
      - backend

volumes:
  sqlite_data:
    # TODO: Für Produktion ggf. Volume Pfad extern speichern oder MySQL/PostgreSQL verwenden